### ISSUE TITLE
clicking 'connect' on the landing page should bring you to the block (just as clicking the thumbnail does) , not straight to a sign up form

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#1004]

**Comment by broskoski** [comment]
Gonna close this, we wanna to optimize for signups right now, and this would take the person further away from that. Is the issue that it is confusing to go straight to login with no context?  Would a "Sign up to Are.na to connect this block" message on the sign up page make it better?

For a similar flow, try favoriting something on Twitter when logged out.
