### ISSUE TITLE
Better error messages for GraphQL errors

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1020]
This should be a 401 not a 500
![screen shot 2018-01-04 at 2 14 47 pm](https://user-images.githubusercontent.com/821469/34580098-afc99ba2-f159-11e7-801e-f9f0e654e8ec.png)

**Comment by dzucconi** [comment]
graphql doesnt have status codes

**Comment by dzucconi** [comment]
sorta

**Comment by broskoski** [comment]
Regardless, this error page shouldn't look like this.

**Comment by dzucconi** [comment]
ok assigning it to @csherron

**Comment by broskoski** [comment]
@dzucconi it just needs to look like what it did before for now.

**Comment by broskoski** [comment]
To reproduce, go to a private channel logged out
