### ISSUE TITLE
add 'share' link to channel descriptions and light box 

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#1026]
updated below

**Comment by csherron** [comment]
!reminder not to include share links on private channels / private blocks

**Comment by csherron** [comment]
updated

click share then 3 options appear

1. Copy link (or "private" link if a private channel (private block?))
2. Twitter
3. Facebook

clicking "copy" still shows orange feedback text 
clicking a "copy private link"  reveals the private share link
![screen shot 2018-01-05 at 1 20 17 pm](https://user-images.githubusercontent.com/3780330/34622965-43045ca4-f21d-11e7-9136-5b6d11375002.png)

![screen shot 2018-01-05 at 1 20 22 pm](https://user-images.githubusercontent.com/3780330/34622974-4ce18594-f21d-11e7-87bc-3a28f555b446.png)
![screen shot 2018-01-05 at 1 22 36 pm](https://user-images.githubusercontent.com/3780330/34622977-50e35a1e-f21d-11e7-9d9c-6cfb10589363.png)
![screen shot 2018-01-05 at 1 26 57 pm](https://user-images.githubusercontent.com/3780330/34622981-52e9cb86-f21d-11e7-8dd7-09733ee55072.png)

**Comment by dzucconi** [comment]
- [ ] always display info column in channel
