### ISSUE TITLE
Copy edits on Education page

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#1064]
- [x] change copy to:

> **Students and educators get 50% off Are.na Premium**
> An Are.na premium membership allows you to save an unlimited amount of private content and gets you access to new features and support.
> 
> Premium normally costs $5 / month or $45 / year, but **students and educators can now take 50% off the price of either membership**. Just enter the coupon **studenthalf** when you [upgrade](https://www.are.na/settings/billing) your account.
> 
> If you’re already enjoying Are.na, please feel free to [invite students or academic collaborators](https://www.are.na/tools/send-invitation) and share this offer with them.

> **About Are.na for Education**
> If you’re a student, you can use Are.na to collect all kinds of research in one place — and structure it all visually. Because you can link their research to anyone else’s, Are.na gives puts a growing archive of shared knowledge at your fingertips.
> 
> If you’re an educator, Are.na is a perfect place to host resources for classes and workshops. Check out our [step-by-step guide](http://s3.amazonaws.com/arena-attachments/1635133/ad5e2459400e0dd0d6f3c07e2c9e686f.pdf?1516720354) to setting up a class on Are.na.
> 
> Keep scrolling to see examples of how students and teachers are using Are.na, or visit our [about page](https://www.are.na/about) to learn more.

> **Examples**
> Click through the examples below to explore how Are.na members are using the platform for teaching and learning in a variety of settings.
>
> **Orthographies**
> A fall 2017 course taught by Lucy Siyao Liu in MIT’s Arts, Culture, and Technology program. Exercises, projects, and references are all clearly organized into channels within the class channel.
>
> **Brand Concepts**
> A fall 2017 course taught by Allyn Hughes at Parsons. Students uploaded PDFs and images of their work to various assignment channels within the class channel.
>
> **Emergent Culture: Production and Strategies**
> A class taught by Karen Wong, Deputy Director of the New Museum, at Columbia University’s Graduate School of Architecture, Planning and Preservation. The class has a dedicated Are.na account, with channels for each session containing readings and assignments.
>
>More examples can be found [here](https://www.are.na/christina-badal/teaching-on-are-na).

[_keep same images and links above_]

> **Contact Us for Support**
> Are you a student, educator, or administrator working with a larger group or an institution? We’re happy to talk through your situation and help you start using Are.na. Send an email to help@are.na to get in touch.
> 
> We’re also working on a whole suite of team features so you can share accounts and manage your content in groups. [Sign up for our monthly newsletter](https://confirmsubscription.com/h/d/728B9103B7704F3A) to get occasional updates.

- [x] make coupon text #00c5ff

**Comment by warshawshaw** [comment]
> "link **your** research to anyone else's
