### ISSUE TITLE
User reports email addresses with '+' signs not working in bookmarklet

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1089]
<img width="614" alt="screen shot 2018-02-01 at 10 04 33 am" src="https://user-images.githubusercontent.com/821469/35685317-5df623b0-0737-11e8-9792-9b77dd8cd8d5.png">

**Comment by dzucconi** [comment]
Should be interesting: it's the same login.

**Comment by broskoski** [comment]
Yeah, I think it might be the wrong direction. Will email them.

**Comment by broskoski** [comment]
This does need a better error screen though!

**Comment by dzucconi** [comment]
If that's error screen that is visible then obviously the JS isn't loading.
