### ISSUE TITLE
Resend confirmation button is hitting a route that 404s

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1090]
<img width="1363" alt="screen shot 2018-02-01 at 10 12 27 am" src="https://user-images.githubusercontent.com/821469/35685715-7083feca-0738-11e8-858b-c748f894f5c9.png">

**Comment by dzucconi** [comment]
WTF. Check that on desktop?

**Comment by broskoski** [comment]
Yeah, same

**Comment by dzucconi** [comment]
That's cuz the email doesn't exist

**Comment by dzucconi** [comment]
`user = User.find_by_email!(params.require(:email))`

**Comment by dzucconi** [comment]
So is this issue for a better error message, or?

**Comment by broskoski** [comment]
No, the email does exist: https://ops.are.na/users/31120

**Comment by broskoski** [comment]
(Otherwise, I wouldn't have been able to log in)
