### ISSUE TITLE
Bookmarklet (and extension) not loading on some sites in Chrome 

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1103]
From an email report: 

- The bookmarklet and Chrome extension do not execute the script. This shows up in the console
- Refused to frame 'https://www.are.na/' because it violates the following Content Security Policy directive: "frame-src 'self' https://www.google.com/recaptcha/"

**Comment by broskoski** [comment]
Possible solution for extension (https://stackoverflow.com/questions/25867584/extension-refuses-to-load-the-script-due-to-content-security-policy-directive/25868498#25868498)

**Comment by dzucconi** [comment]
https://medium.com/making-instapaper/bookmarklets-are-dead-d470d4bbb626

We should just move to exclusively using extension anyway.
