### ISSUE TITLE
Drag and drop reordering broken

### ISSUE THREAD

**Issue by dzucconi** [aredotna/ervell#1106]
## Steps to replicate
* Open an editable channel
* Try to re-order the blocks

## Expected result
Block should move to new position.

## Actual result
Block gets duplicated. Chrome logs the error:
`Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

**Comment by dzucconi** [comment]
When did this start working again :?

**Comment by broskoski** [comment]
Probably the same error that was happening on pages with no collaborators

**Comment by dzucconi** [comment]
Nah, twasn't

**Comment by broskoski** [comment]
Well, how would it have been fixed otherwise, hotshot?
