### ISSUE TITLE
Edit collaborator link not showing up if user does not own channel (but is a collaborator)

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1144]
## Steps to replicate
* Visit a channel you don't own but are a collaborator on

## Expected result
Edit collaborator button should show up

## Actual result
It does not

![screenshot 2018-03-19 13 23 46](https://user-images.githubusercontent.com/821469/37611451-c5f04cf6-2b78-11e8-9e4d-23c719a42ef5.png)

**Comment by dzucconi** [comment]
Yeah, I'm waiting to work on this: the idea here is that we need to check for a new can type `can.manage.your_membership` or some such.

**Comment by broskoski** [comment]
We _should_ allow _any_ collaborator to add and remove collaborators in a channel, though I don't think that is reflected in the ability model.

**Comment by dzucconi** [comment]
It is: you can manage a membership if you own it (the individual membership not adding/removing to the channel context). This just isn't reflected in the can type.

**Comment by broskoski** [comment]
Right, I'm saying that you should be able to add new people and remove them in addition to that.

**Comment by dzucconi** [comment]
Oh. Interesting. Well that's easier.
