### ISSUE TITLE
User should be able to remove themselves from a group

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1160]
## Steps to replicate
* Get added to a group by another user
* Try to edit that group after the fact

## Expected result
You should see the "edit group" modal and be able to remove yourself (but not change the group title or delete the group)

## Actual result
No "edit" button appears

**Comment by dzucconi** [comment]
Can you remove other people?

**Comment by dzucconi** [comment]
Presumably yes. Since that's the behavior for everything.

**Comment by broskoski** [comment]
I can see arguments either way. My first thought is no, but if it makes things clearer then godspeed.

**Comment by dzucconi** [comment]
Why is your first thought for this no but also think you should be able to remove the anyone else from the channel itself?

**Comment by broskoski** [comment]
A group "feels" more substantial than a channel. This is obviously very subjective so go with your gut.
