### ISSUE TITLE
deleting a group gives me an error - bottom button says 'error'

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#1162]
## Steps to replicate
- create a group
- leave channel
- visit channel again
- edit group
- click delete and confirm

## Expected result
- edit group modal should close, group is gone from metadata

## Actual result
- edit group stays open, wide bottom button says 'error' and is grayed out, unable to click
- upon refresh, it seems that group is gone

**Comment by dzucconi** [comment]
I'm having trouble replicating. @broskoski can you confirm and give me the error or help @csherron pull the error out for me?

**Comment by csherron** [comment]
try adding group to a few channels, then delete the group from one of those, not the original channel the group was created in?

**Comment by dzucconi** [comment]
Weird, still can't replicate.
