### ISSUE TITLE
New static pages

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#1189]
- [x] blog index
https://zpl.io/2Zxpxmd

- [x] blog post
https://zpl.io/V4AKAdM

- [x] projects
https://zpl.io/2EwDw9x

- [x] about
https://zpl.io/bzYJYR8

- [x] pricing
https://zpl.io/amBgBwA

- [x] education
https://zpl.io/Vq6965N

- [x] replace "Team" link in footer with "About" and link to new about page

- [x] add link to Store in footer:
Company
**About
Media Kit
Store
FAQs**

**Comment by broskoski** [comment]
(Pricing copy: https://docs.google.com/document/d/1ZUNdmcWXHLYN-HUgoYeA4rrf5AY9xOPBf8K9vKNkQ4s/edit)
