### ISSUE TITLE
User feedback that bookmarklet is not working on Firefox

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1201]
> hey there, i'm having some trouble with the bookmarklet on Firefox. Everything seems to work fine on Chrome, so I assume this is a classic case of Firefox not getting much love.

**Comment by autonome** [comment]
That previous error was on Github, using Firefox nightly, and no are.na UI showed up at all.

Went to localhost and tried it, and the UI did appear, but wasn't really functional. There were errors in the console, which I logged: https://pastebin.mozilla.org/9086166

**Comment by autonome** [comment]
Ah, apparently Github won't work with any bookmarklet in any browser because all browsers implement CSP incorrectly 😭

https://blog.github.com/2013-04-19-content-security-policy/

**Comment by autonome** [comment]
The errors in other non-Github sites don't look like CSP related though. Haven't dug further into it yet tho.

**Comment by autonome** [comment]
Hi @broskoski, is this working now?

I just went to try and install the bookmarklet here: https://www.are.na/tools/bookmarklet

But there's no bookmarklet anymore, just a link to the extension?

**Comment by autonome** [comment]
Related, this might have fixed the previous bookmarklet issues:

https://bugzilla.mozilla.org/show_bug.cgi?id=1478037

**Comment by broskoski** [comment]
For Firefox and Chrome we just direct people to the extension. Though we should probably do detection on the bookmarklet itself for and direct anyone with Chrome or Firefox installed to use the extension instead.

**Comment by autonome** [comment]
I'd really prefer to use a bookmarklet. It would be great if the user was
able to make the decision of which to use.

**Comment by broskoski** [comment]
Interesting, can you tell me more about why? In any case, would be an easy fix.

**Comment by autonome** [comment]
Sure!

* Extensions like this usually don't take a ton of resources, but more than the near-zero cost of a bookmarklet. I've got a lot of extensions that do real work, so for anything like this I try to use the bookmarklet.

* Extensions force me click the button in a specific area on toolbar with limited shelf space, or have one (typically unconfigurable) keyboard shortcut hardcoded. A bookmarklet I can place anywhere on the toolbar, and I have many ways of executing it.

* I run an extension that gives me a GCLI for executing bookmarklets when I don't have my bookmarks toolbar open.

Also, from years of working on browsers: There's a cognitive load the "install" of extensions that a subset of users will immediately reject. Keeping as many pathways for users to interact with your service as possible is the best strategy, especially if it's super low cost like a plain ol' URL to a simple posting interface on the website.
