### ISSUE TITLE
Broken channel links on Profile post-username change

### ISSUE THREAD

**Issue by stephenkistner** [aredotna/ervell#1247]
## Steps to replicate
* visit user profile
* if user changes their name, links to pre-name-change channels still contain the old name in the URL — which breaks the links

## Expected result
URLs should change based on user name changes, or be independent of usernames altogether.

## Example

Visit my [profile](https://www.are.na/steve-k/index) and then click on my "neon, plants and lava lamps" chan — notice the URL contains my current username `steve-k`.

Now click on my "ideas" channel — and notice the old username `stephen-kistner-1506347484` which also returns a 404.

**Comment by broskoski** [comment]
Thanks, resolved on the API side.
