### ISSUE TITLE
Clicking links in the sidebar in the welcome tutorial breaks backbone.history

### ISSUE THREAD

**Issue by jaredpereira** [aredotna/ervell#1257]
## Steps to replicate
1. Navigate to [the welcome page](https://www.are.na/welcome/channels)
2. Click any of the links in the sidebar other than `2. Connecting`

This results in this uncaught error: `Backbone.history has already been started`

## Expected result
Those links should take you to the page required

## Actual result
Errors out and the site doesn't load.

**Comment by dzucconi** [comment]
to accept dashes
