### ISSUE TITLE
Stripe sends notice to update expired card but billing info is gone

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#1281]
## Steps to replicate
1. User is subscribed
2. Their card expires
3. Stripe attempts charge, fails, sends email to update their card

## Expected result
4. User goes to /settings/billing and updates their card info

## Actual result
4. User goes to /settings/billing but their billing info is gone, they have to pick a plan again and re-enter the info

**Comment by dzucconi** [comment]
So at some point we have to remove this data, no? We can't just try forever and then keep around their plan/billing information. What's that limit?

**Comment by danpia** [comment]
Yes, but at least wait the 4th attempt, when Stripe officially marks the customer as inactive and removes the subscription? Or we can decide a grace period.

**Comment by dzucconi** [comment]
I believe that's a setting on Stripes end

**Comment by dzucconi** [comment]
So wait, you can actually replicate this? Or this happened once and that's the current theory as to why?

**Comment by dzucconi** [comment]
Also, fwiw: we don't store any of this data. This is entirely within Stripe's realm so whatever funny business happened it's either because of the user or because of some configurable Stripe behavior. If there's gaps in the event log then maybe open a ticket with Stripe.

**Comment by danpia** [comment]
Ok, I thought we were storing that data separately

**Comment by dzucconi** [comment]
In general we try to know as little as possible. You can see the fields here: https://github.com/aredotna/api/blob/master/app/models/customer.rb we just have the ID to the stripe record (external_id) and the plan type/start date/end date.
