### ISSUE TITLE
Update follow count on channels when follow button is pressed.

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1295]
I went through the code a little bit to see how this would work, and it's unclear. This is obviously not that important, I'm more curious about what strategy one would take if they wanted to implement this (seemingly) simple thing.

**Comment by dzucconi** [comment]
Yeah, the only real reason I didn't do this was I had thought we got rid of the counts. Refetching is the answer. Doing it optimistically is semi-annoying.

**Comment by dzucconi** [comment]
By refetching the query in question by passing it in from the parent.

**Comment by broskoski** [comment]
Ah yes got it.

**Comment by dzucconi** [comment]
Or, potentially, just using the type/id information to fetch the model normally which would update the cache. The only wrinkle there being our use of slug/id.

**Comment by broskoski** [comment]
I wonder if the slug / id wrinkle is why this isn't happening automatically: https://www.apollographql.com/docs/angular/features/cache-updates.html#automatic-updates

On second thought, no, its probably bc the followable query is being labeled as `Followable:[id]`
