### ISSUE TITLE
Search results page header/metadata update

### ISSUE THREAD

**Issue by dzucconi** [aredotna/ervell#1300]
Needs to be updated to match.

**Comment by broskoski** [comment]
Some more notes here: 

This is mostly just a styling update but a chance to pull in some of the new React components we've been building for new UI.

---

Here is how the current search header looks:
<img width="1015" alt="screen shot 2018-07-11 at 10 06 38 pm" src="https://user-images.githubusercontent.com/821469/42608639-b6bff65e-8556-11e8-85bc-11274939e4c7.png">

vs the Explore page:

<img width="991" alt="screen shot 2018-07-11 at 10 07 06 pm" src="https://user-images.githubusercontent.com/821469/42608652-cc72c90e-8556-11e8-82de-dbbeb4e4cf38.png">

---

So all that needs to happen here is replacing the jade template there (on the path and the 'view' column) to use the new components, found in: https://github.com/aredotna/ervell/tree/master/react/components/HomeMetadata
