### ISSUE TITLE
Website embed takes over block view

### ISSUE THREAD

**Issue by msutherl** [aredotna/ervell#136]
Didn't investigate at all what's going on here, but umm ...

![screenshot 2015-08-07 18 04 02](https://cloud.githubusercontent.com/assets/31774/9146932/fd0f7d00-3d2e-11e5-99ec-931f8c589bd0.png)

This is the block view for https://cocatopia.wordpress.com/about/

**Comment by danpia** [comment]
for some reason the site is displayed with the "media" div (like videos) instead of img one (for screenshots). Any clue @broskoski ?

**Comment by dzucconi** [comment]
This appears to be fine if I add this URL now.

There does appear to be a pretty wild `embed_html` for that ID; but I can't take a look at the block itself because it's in a private context.

It's not a terrible idea to sandbox unknown embeds within an `iframe`, however.
