### ISSUE TITLE
swap linked PDF on education page

### ISSUE THREAD

**Issue by warshawshaw** [aredotna/ervell#1370]
Replace the linked file on the education page where it says **step-by-step guide**

New PDF attached here

[Are.na for Educators.pdf](https://github.com/aredotna/ervell/files/2189434/Are.na.for.Educators.pdf)

**Comment by broskoski** [comment]
Two quick changes: 

- [ ] Mention the mobile app (maybe in Add content or Save content sections)
- [ ] Coupon code should be "education" instead of "studenthalf"

**Comment by warshawshaw** [comment]
bump :)
