### ISSUE TITLE
Error messages on new forms should have error borders

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1401]
## Steps to replicate
* Go to sign up form
* Input mismatched passwords
## Expected result
Border of form field should be colored differently

## Actual result
Form field border stays black

![screen shot 2018-08-10 at 1 51 26 pm](https://user-images.githubusercontent.com/821469/43973103-806329d6-9ca4-11e8-93ec-8644d7eaa92a.png)

**Comment by dzucconi** [comment]
gah regression, this *was* working
