### ISSUE TITLE
Sign up form tabbing should work for check boxes and button

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1403]
## Steps to replicate
* go to are.na/sign_up
* tab through fields

## Expected result
You should eventually be able to land on check boxes

## Actual result
You get tabbed into the address bar

**Comment by dzucconi** [comment]
You can tab to them btw; they just don't have a focus style

**Comment by dzucconi** [comment]
This looks straight up not possible without a custom checkbox implementation.

**Comment by dzucconi** [comment]
Tabbing checkboxes is an accessibility feature in Safari that needs to be turned on apparently.
