### ISSUE TITLE
Resetting password with an unconfirmed account

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1405]
## Steps to replicate
* Reset a password with an account that is unconfirmed for more than 3 days

## Expected result
* You should get logged in and then displayed an error message saying that your account is unconfirmed, with instructions for how to get it confirmed.

## Actual result
Form submit button gets stuck on "Logging in...", network console reveals a 401 unauthorized.

**Comment by dzucconi** [comment]
Wait—I can't replicate this. It just resets.

**Comment by dzucconi** [comment]
Oh *sends* not resets
