### ISSUE TITLE
Login Form on Firefox does not fire onChange events if login is autofilled.

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1443]
## Steps to replicate
* Turn autocomplete on in Firefox
* Sign in
* Log out and sign back in again

## Expected result
If the element is prefilled, you should be signed in normally.

## Actual result
The page REFRESHES. No error's thrown, all required fields and validation ignored.

Nothing about the way Firefox handles forms in this state makes any sense. Even upon setting a `ref` for each form element and inspecting their values on `componentDidMount`, the `value` field was completely empty. EMPTY.

**Comment by broskoski** [comment]
Twitter thread regarding this: https://twitter.com/dietrich/status/1034133399508680704

Issue outlining the various browsers that have had this issue over the months: https://github.com/facebook/react/issues/1159

Tried this polyfill (to no avail): https://github.com/Pephers/react-autofill

My current theory, autofill (and its event) is happening on the server rendered form (prior to React initializing, hence no event fired)

**Comment by dzucconi** [comment]
Another related React issue: https://github.com/facebook/react/issues/11097

For solutions there's this:
There's this https://github.com/chrisblossom/react-safe-universal-inputs —which appears to be minimal. If used we need to add some comments with links tracking the issue.

**Comment by dzucconi** [comment]
The other option is to just turn off autocomplete for now.
