### ISSUE TITLE
Dropdowns Q/A

### ISSUE THREAD

**Issue by dzucconi** [aredotna/ervell#1480]
# Notifications
- [x] Empty state for notifications
![](http://static.damonzucconi.com/_capture/bsppucOsSb.png)

# User
- [x] Slightly less vertical padding on large items

**Comment by csherron** [comment]
### Top bar

- [ ] new hover states for 'new channel', notifs, and avatar

![screen shot 2018-09-14 at 4 44 01 pm](https://user-images.githubusercontent.com/3780330/45574279-7fb6c380-b83d-11e8-9ed3-666bf615cd76.png)

**Comment by csherron** [comment]
can the notifications dropdown be invisible until one starts receiving notifications?

**Comment by dzucconi** [comment]
Hm, off the top of my head no, not *currently* possible; but I think having some kind of decent empty state is a fine idea rather than having the UI move around.
