### ISSUE TITLE
Can't drag bookmarklet on Chrome 69 bar

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#1508]
## Steps to replicate
Install Chrome Version 69.0.3497.100 (Official Build) (64-bit)

## Expected result
Bookmarklet installs

## Actual result
Doesn't even add to the bar

![book](https://user-images.githubusercontent.com/3718189/46009751-bfdd3800-c0c0-11e8-96ab-3002ff9ee1a5.gif)

**Comment by dzucconi** [comment]
You can no longer drag *any* links into the bookmark bar.

https://bugs.chromium.org/p/chromium/issues/detail?id=878392

I suspect there'll be a patch soon?
