### ISSUE TITLE
Use `item_title` for notifications

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1512]
## Steps to replicate
* Get a notification without a title

## Expected result
The notification item should fall back to the type of item (e.g. User added **a text** to Channel)

## Actual result
It does not

![screen shot 2018-09-27 at 2 52 47 pm](https://user-images.githubusercontent.com/821469/46168015-46cb1580-c265-11e8-80ae-928e564d1a0c.png)

**Comment by dzucconi** [comment]
what the what

https://github.com/aredotna/ervell/blob/417d1d964a6f70e40b1cc9186af26993474dc89b/react/components/NotificationsDropdown/components/Notification/fragments/notificationObject.js#L16

**Comment by dzucconi** [comment]
in this case it'd be Untitled Text. Why would title return 'a text'? Is that an arg?

**Comment by broskoski** [comment]
`item_title` is an attribute on `DeedType` which handles falling back to types.

**Comment by dzucconi** [comment]
oh word. Wanna PR?

**Comment by broskoski** [comment]
Sure.
