### ISSUE TITLE
new feed QA

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#1516]
- [x] feed sentence text links are missing hoverstates
- [x] 10px more padding between line and feed sentence
- [x] 10px more padding below the timestamp
- [x] in the feed clicking cmd+source sends you to the new tab, while on channels stays on are.na with the new tab on background (imo the latter is preferable)
- [x] in the feed there's a source button for images 
- [x] seems like there's no max-width for the feed sentences, might stretch too much on big screens

**Comment by danpia** [comment]
- [ ] in the feed clicking cmd+source sends you to the new tab, while on channels stays on are.na with the new tab on background (imo the latter is preferable)
- [ ] in the feed there's a source button for images 
- [ ] seems like there's no max-width for the feed sentences, might stretch too much on big screens
