### ISSUE TITLE
Profile contents should handle processing blocks

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1565]
## Steps to replicate
* Go to https://www.are.na/ilnur-mustafin/channels

## Expected result
Channels view should display

## Actual result
Error gets thrown for a type of block that does not fit the accepted types:

```
[konnectable.__typename] is not a function
```

**Comment by dzucconi** [comment]
i agree but shouldn’t they not be indexed?

**Comment by broskoski** [comment]
Query hits `blokks` (which hits the db): https://github.com/aredotna/ervell/blob/master/react/components/ProfileChannels/fragments/profileChannels.js#L32

**Comment by dzucconi** [comment]
pretty sure only for groups. same resolvers different types
