### ISSUE TITLE
Group special characters together on channel index.

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1597]
## Steps to replicate
* Go to profile index view

## Expected result
Channels with special characters should be grouped together
## Actual result
They are grouped individually?

This is coming from a req on Are.na community slack:

![screen shot 2018-12-10 at 11 15 41 am](https://user-images.githubusercontent.com/821469/49745509-1e9c6180-fc6d-11e8-90f5-bac1ec4414ff.png)

**Comment by dzucconi** [comment]
She wants the opposite of what you're describing. I also disagree with this request.

**Comment by broskoski** [comment]
@dzucconi I'd like to continue the habit of responding to requests, so give me a little more rationale if you disagree

**Comment by dzucconi** [comment]
There's also a bunch of different alternatives: transliterate them and group with corresponding alpha characters; strip them and group by the first letters.

What about numbers, does 0-9 each get their own category?

**Comment by dzucconi** [comment]
How does one ascertain a single request represents what everyone wants? I want the opposite so how do we reconcile.

For instance this channel: http://static.damonzucconi.com/_capture/BPbOhYyslw.png
Do you believe that should be under the heading `/` or `U` or `#`?
