### ISSUE TITLE
Import of bookmarks from HTML 

### ISSUE THREAD

**Issue by davidmooreppf** [aredotna/ervell#162]
Totally no worries on this, don't even know the details of the [data model for blocks](https://github.com/arenahq/ervell/blob/develop/models/block.coffee), just wondering - if my goal is to import my del.icio.us bookmarks from their simple HTML file export, that'd be cool to have an upload button for those. But it also might go against some of the Are.na specific research goals & user stories. Lot of old & text links if other users started using it. Could have emailed this question to Cab but wanted to poke around a bit first. After all, del.icio.us '05 links were pretty different than now. 

PRIORITY: MAJOR

**Comment by broskoski** [comment]
@davidmooreppf yeah definitely! We have been toying with this idea for a while, but you bring up a good point, their HTML export is probably the easiest to parse. My hope is that some of the architecture that will need to get built for Pilgrim, will have a side effect of making it easier to drop many resources into a channel at once, which would then make it much less of a burden to make a tool to import links from a specific platform.

MESSAGE: RECEIVED

**Comment by davidmooreppf** [comment]
STATUS: WORD / COOL
