### ISSUE TITLE
Can't confirm channel transfer

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#1654]
## Steps to replicate
I transferred two channels owned by https://www.are.na/no-plans
to the group https://www.are.na/no-plans-jecvaz3bh8m (owned by daniel-pianetti)

## Expected result
When I click the confirmation email it should transfer

## Actual result
We are unable to handle this transfer.
You are not authorized for this action. You may be logged into the incorrect account.
If you are experiencing difficulty transferring a channel, contact us at help@are.na.

**Comment by dzucconi** [comment]
Channel IDs?

**Comment by danpia** [comment]
https://www.are.na/no-plans/research--17
https://www.are.na/no-plans/work-by-no-plans
