### ISSUE TITLE
group badge tweaks

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#1714]
- [x] group badge lock symbol should be to the **left** of ‘GROUP’ text, not right
- [x] on quick search items 
- [x] in connect search results for connect block and bookmarklet (but not mini connect)
- [x] group badges in connect and bookmarklet (but not mini connect) end up resizing the cell, the height should remain the same regardless of badge or not - if its a matter of sizing then make the badge itself smaller

**Comment by dzucconi** [comment]
I sort of don't really understand any of these issues actually; chat me

**Comment by dzucconi** [comment]
@broskoski these are all in the stylus/jade bits

**Comment by broskoski** [comment]
@dzucconi will do

**Comment by csherron** [comment]
screengrabs:
<img width="413" alt="screen shot 2019-01-17 at 2 17 39 pm" src="https://user-images.githubusercontent.com/3780330/51342827-e43f9480-1a62-11e9-8b94-39652113901a.png">
<img width="354" alt="screen shot 2019-01-17 at 2 17 59 pm" src="https://user-images.githubusercontent.com/3780330/51342828-e43f9480-1a62-11e9-926f-f0021296d5ec.png">
