### ISSUE TITLE
Updated styling and logic to new account banner system

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1786]
#### Styles:
![frame 4](https://user-images.githubusercontent.com/821469/52595053-f7a00e80-2e1a-11e9-9731-bdc7a38f601b.png)
Figma link: https://www.figma.com/file/Ji52dCnxPrKYCdmWHCjcsO3C/Styles?node-id=1782%3A0

#### Logic:

1. Confirm email banner appears 24h after signup (Yellow, with clipboard icon, no close button)
"Please check your email to confirm your account. Haven't received an email yet? [Resend confirmation email]"

2. After email is confirmed: Bookmarklet/Extension banner (Yellow with ? icon)
"Save content from any website with the Are.na bookmarklet. [Install]"

3. When above is performed OR closed: Invite friends banner (Yellow with i icon)
"Invite friends to collaborate on Are.na. [Send invite]"

#### Overrides (these conditions should override any of the above)

1. User has 2 or more private channels: Premium offer (Premium blue, exclamation icon)
"Get unlimited private content and save 25% when you upgrade to Premium with the coupon code garden. [Learn more] (/settings/billing)" 

2. When account hits block limit: Premium upgrade (Premium blue, exclamation icon)
"You've run out of free private blocks. Please **upgrade to Premium** to keep working privately"

#### General behavior notes / questions
- We don't want banners to pop-up immediately after another banner is closed (or ever pop-up after a page refresh), how do we build in some buffer time in between them?

**Comment by dzucconi** [comment]
@csherron @broskoski how do we want to handle existing users. they wont see the confirm but they will see the invite/bookmarklet.

invite we can handle by saying ok if you havent sent an invite before then ur getting it regardless of age of account.

what about bookmarklet? have they been a user for x months?

**Comment by broskoski** [comment]
@dzucconi how about user less than two weeks old?

**Comment by dzucconi** [comment]
works for me
