### ISSUE TITLE
Lightbox drag issue

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#179]
## Steps to replicate
* Drag an image in lightbox (activates the channel drop in the background)
* Close lightbox

## Expected result
Should upload on drop or remove the drop notification

## Actual result
Drop dialogue stays and you are forced to refresh

**Comment by dzucconi** [comment]
Unsure if this is still valid but leaving it open for now.

**Comment by broskoski** [comment]
Can't replicate
