### ISSUE TITLE
after creating a single group, there exists too much blank space in group area

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#1804]
<img width="383" alt="screen shot 2019-02-14 at 5 15 28 pm" src="https://user-images.githubusercontent.com/3780330/52821241-397bbf80-307c-11e9-81c5-1f1a35aac2ea.png">

group area should fit to the amount of groups in the list

**Comment by dzucconi** [comment]
Yeah, this one got fixed but isn't deployed yet.
