### ISSUE TITLE
Night mode short cut doesn't trigger on profile pages

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1810]
## Steps to replicate
* ctrl+shift+I on a profile page

## Expected result
Night mode triggered

## Actual result
No worky

**Comment by dzucconi** [comment]
oh i used cmd+ctrl+shift+i lol
https://github.com/aredotna/ervell/blob/fbbda5197ec995a356f13261113f88473f5c5b63/react/util/globalKeyboardShortcuts.js#L11

**Comment by dzucconi** [comment]
HOWEVER: to me this seems like a ridiculous thing to be a keyboard shortcut. I'm of the opinion this should just be a setting so it's not turned on accidentally and it's clearer.

**Comment by broskoski** [comment]
Sure agreed (little toggle in user dropdown could be nice), but right now its a different conversation
