### ISSUE TITLE
Log in via the form and pressing return takes you to a 404

### ISSUE THREAD

**Issue by orta** [aredotna/ervell#182]
did this: https://www.are.na/log_in
typed in details, pressed return:

![screen shot 2015-12-07 at 10 36 57 am](https://cloud.githubusercontent.com/assets/49038/11631098/74211ed6-9cce-11e5-8007-22b35d7d1c4d.png)

**Comment by broskoski** [comment]
Fixed a while ago, forgot to close this. Thanks @orta !
