### ISSUE TITLE
Follow button misaligned when toggled in channel

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#1841]
## Steps to replicate
* Hit follow on channel

## Expected result
"Unfollow" should be aligned with the mute button

## Actual result
It is misaligned

![screenshot 2019-02-28 17 16 11](https://user-images.githubusercontent.com/821469/53602422-b9298400-3b7c-11e9-83d8-cb5eb70714e9.png)

**Comment by csherron** [comment]
this misalignment also happens on private channels with the mute / edit channel buttons
