### ISSUE TITLE
Search issues log

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#185]
<img width="213" alt="screen shot 2015-12-14 at 1 50 49 pm" src="https://cloud.githubusercontent.com/assets/3780330/11790431/cb48385c-a269-11e5-8acc-d1b1df2f9255.png">

**Comment by csherron** [comment]
only works if i search last name only

**Comment by danpia** [comment]
searching 'brand' won't display '[brand]'
searching 'hardware' won't display 'TTHardware'

**Comment by danpia** [comment]
the priority order seems random sometimes, in these case there are two other channels named services that should show up because I recently updated
![unspecified](https://cloud.githubusercontent.com/assets/3718189/12201116/7a166612-b5f0-11e5-9924-193d63c57a66.png)

**Comment by danpia** [comment]
suggestion received: be able to quickly scope a search by user from the main search  bar

**Comment by danpia** [comment]
can't search one-letter channels/users

**Comment by danpia** [comment]
not a priority but would be good to ignore accents when searching (right now "etudes" doesn't search for "études")

**Comment by danpia** [comment]
<img width="1421" alt="screen_shot_2016-02-08_at_9 31 22_am" src="https://cloud.githubusercontent.com/assets/3718189/12891441/fe2993c0-ce55-11e5-9df9-32930a0280ed.png">

**Comment by danpia** [comment]
![unspecified-20](https://cloud.githubusercontent.com/assets/3718189/12925050/77fd87a4-cf2a-11e5-87d5-a48c974b78f2.png)
"listening right now" should be the first result here

**Comment by danpia** [comment]
"studio" returns correctly "damon zucconi - studio" because I follow it
If I keep typing "studio damon" it disappears showing other not relevant channels. 

Ideally the fact that both words are contained in the search string should be stronger than the order of words.

**Comment by danpia** [comment]
"Cinema (container)" channel doesn't appear in results because I search only "Cinema" https://www.dropbox.com/s/k3lx0p6t9ags0ju/Screenshot%202016-03-31%2018.37.09.png?dl=0

**Comment by danpia** [comment]
When visualizing the search as "All" the results are right, when I click "Channels" only it's completely messed up: 

![unspecified](https://cloud.githubusercontent.com/assets/3718189/14290157/ee225130-fb2b-11e5-961d-53db8c6a69a1.png)
![unspecified-1](https://cloud.githubusercontent.com/assets/3718189/14290160/f2681fc2-fb2b-11e5-8327-80b1084214a7.png)

**Comment by danpia** [comment]
User search feature suggestions:
- Search a block present in two or more channels, with an advanced search, I could search blocks connected to a “Print” channel and also present in a “Layers” channel
- An option to narrow down a search to “URL”, “text”, “img” only

**Comment by danpia** [comment]
can't search for urls 
https://www.dropbox.com/s/cn5a4v6vtqeiyg7/Screenshot%202016-10-07%2011.16.15.png?dl=0

**Comment by dzucconi** [comment]
Should be able to search usernames and channels e.g. “morgan silicon” = Morgan's "Silicon Valley" channel (from: https://github.com/aredotna/ervell/issues/265)

**Comment by dzucconi** [comment]
https://github.com/aredotna/api/issues/24

**Comment by dzucconi** [comment]
I wonder if every app with a non-trival search feature has an issue like this? (Remembering Artsy's)

**Comment by danpia** [comment]
closing because several of these are solved, and moving the others to the official Search audit topic on basecamp
