### ISSUE TITLE
feed items are currently only 3 blocks wide

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#1963]
currently the feed width is squeezed down to only fit 3 blocks

feed items used to be 4 blocks wide

would be nice to accommodate bigger screens by making the feed up to 7 blocks wide

**Comment by dzucconi** [comment]
The offending line https://github.com/aredotna/ervell/blob/b63a4df3e56baeb0699c0f0a47dbdd6c73b7db58/react/components/Feed/components/FeedGroups/index.js#L51
