### ISSUE TITLE
Youtube links broken

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#1969]
Thumbnail isn't happening when pasting youtube links

**Comment by dzucconi** [comment]
It looks like YouTube is blocking Embedly's proxy?

https://i.embed.ly/1/image?url=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fof_F-Nhpvm8%2Fhqdefault.jpg&key=6323bba27b4e4526b49600976272dad5

The actual thumbnails are fine: https://i.ytimg.com/vi/of_F-Nhpvm8/hqdefault.jpg

We'll have to write something to fallback; I'm not even sure why we would want them to proxy the images actually. Going to move this issue to API
