### ISSUE TITLE
can't upload images from ipad (while on phone works)

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#208]

**Comment by danpia** [comment]
it's actually a stupid error: the rule of displaying `.add-block__placeholder` instead of `.plus-placeholder` fires only at the max-width:500px while it fire either with handheld rule or for max-width:1024px

![unspecified-4](https://cloud.githubusercontent.com/assets/3718189/17464668/71e06614-5cb2-11e6-9a18-bb67e11fb1cc.png)

**Comment by dzucconi** [comment]
I believe this is fixed.
