### ISSUE TITLE
Edit block cover image specs

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#2167]
I'd keep it pretty simple, my only doubt is if it should it be after Mute.

Specs:
- only original owner of the block can change
- only premiums can change
- if you're not premium, the button links to /pricing

@csherron design-wise this is an opportunity to start thinking about a "grayed out" prompt system for Premium features, for example later on I could even see something in your profile like "Hide your profile from search engines". I don't mind using the blue stars as an icon for now, I remember there were some doubts about the checkmark as Premium symbol, but if you have any ideas (i.e. more of a buttony feeling) feel free to let us know.

![edit-thumb](https://user-images.githubusercontent.com/3718189/64494302-12275280-d259-11e9-8b8a-2250336a5602.png)

**Comment by csherron** [comment]
awesome
