### ISSUE TITLE
New favicon

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#2176]
![favicon](https://user-images.githubusercontent.com/821469/64909468-9440cc80-d6da-11e9-9220-7c9c3419ef87.png)

(Optimized for dark mode, thanks to Jonathan Simcoe)

**Comment by jdsimcoe** [comment]
Hopefully this PR solves it @broskoski. I provided a 32 x 32 `png` file but saw that your codebase had a `favicon.ico`. I created an optimized `.ico` file that includes `16x`, `32x`, `48x`, and `256x` sizes to accommodate all sizes included Windows browsers.
