### ISSUE TITLE
Lightbox on Audio Block / Pointer Events

### ISSUE THREAD

**Issue by mattwolff** [aredotna/ervell#2340]
Hello, I was just messing around with some audio files and noticed I couldn't scrub through them with the lightbox open... 

## Steps to replicate
1. Open the Lightbox for any Block with an audio file. [Here's one](https://www.are.na/block/1606629)
2. Click the play and start playback on the `audio` element. 
3. Interact with playback progress or volume controls.

## Expected result
Progress or volume for the `audio` element should update accordingly.

## Actual result
You're dragging on the wrapping link to the file. 

Here's a screen recording of this issue happening on a desktop in Chrome:
![audio-element-v2](https://user-images.githubusercontent.com/21694984/82379122-6132a380-99f4-11ea-9e02-c7bd720ae988.gif)

Similar behavior in Firefox and Safari. FWIW: In Safari clicking play on the audio element starts playback in the lightbox and also opens up the AWS link in a new tab where it also starts playing too. (Double audio playback). Haven't looked on mobile / App.

**Comment by broskoski** [comment]
Thank you so much for this detailed bug report. I will fix this immediately to show my appreciation.
