### ISSUE TITLE
Weird comment  double glitch

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#245]
If I edit it I see it correctly, but as soon as I post it renders like this. Link to profile works. 
![screenshot 2016-07-27 14 15 16](https://cloud.githubusercontent.com/assets/3718189/17186829/d2db80fe-5404-11e6-97d1-29268e36b1cc.png)

**Comment by danpia** [comment]
![screenshot 2016-07-27 14 25 08](https://cloud.githubusercontent.com/assets/3718189/17187139/046be6da-5406-11e6-8e00-d462318581a3.png)

**Comment by dzucconi** [comment]
Feel free to re-open if still an issue.
