### ISSUE TITLE
Our chrome extension logs saved websites as inbound links in Google Analytics

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#253]
now that more people are using it it's messing up metrics

![unspecified-9](https://cloud.githubusercontent.com/assets/3718189/18042992/2b4200a4-6dc5-11e6-8037-baaedd3145be.png)

**Comment by dzucconi** [comment]
Re-open if this is still an issue.

**Comment by danpia** [comment]
Still happening. See below i.e. Viceland, abcdinamo don't have are.na links as far as I know.
![screenshot 2017-07-06 09 44 38](https://user-images.githubusercontent.com/3718189/27913984-c66c88f6-622f-11e7-8d16-f4ae465965da.png)
