### ISSUE TITLE
Safer perks storage

### ISSUE THREAD

**Issue by esafev** [aredotna/ervell#2919]
I found that coupons and links to perks are stored in codebase as plain text. I think it is better to store it more safely, as an example in `.env` file.

**Comment by esafev** [comment]
Looks like the issue is no longer relevant, as this repo is now deprecated. Will close it

**Comment by gary-host-laptop** [comment]
> Looks like the issue is no longer relevant, as this repo is now deprecated. Will close it

hello, what do you mean this repo is depreceated, what is the actual front end for are.na now?

**Comment by esafev** [comment]
> > Looks like the issue is no longer relevant, as this repo is now deprecated. Will close it
> 
> hello, what do you mean this repo is depreceated, what is the actual front end for are.na now?

Unfortunately the new are.na client is closed-source at the moment
