### ISSUE TITLE
URL connections bug with tumblr images

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#297]
See: https://www.are.na/block/706121

**Comment by dzucconi** [comment]
Not sure what the bug is. Feel free to re-open.

**Comment by danpia** [comment]
When connecting an image from a Tumblr URL (or maybe even with a Tumblr file name?) the "BLOCKS WITH THIS URL ALSO APPEAR IN" list shows dozens of channels with other, different, Tumblr images.

**Comment by dzucconi** [comment]
I totally don't really understand that feature. @broskoski why would you use the top level domain and not the exact URL? Realistically we could just store SHAs for everything and use that.

**Comment by danpia** [comment]
It was was a first step against duplicate blocks (if you see your block already exists in a channel you might want connect the existing one and find out a similar channel exists), it should obviously be exact URL for images

**Comment by dzucconi** [comment]
Actually, after talking with @broskoski it sounds like this is not a bug but rather an untended consequence of a feature I don't really grok the value of.

Connections should be: "This thing is also within this other context"
Not: "Other things from a similar context are in these other contexts"

So the question here is: which one do we want?
