### ISSUE TITLE
Using the search to filter a channel breaks add block

### ISSUE THREAD

**Issue by dzucconi** [aredotna/ervell#331]
Replicate by loading a channel, typing anything, deleting it so that the add block field returns. 

Assuming some events not being re-bound on re-render.

**Comment by dzucconi** [comment]
I've also noticed this occasionally breaking on initial render but I haven't been able to replicate. A refresh usually clears that up.

**Comment by broskoski** [comment]
Man can't replicate this either, what version of Chrome....seriously.

**Comment by dzucconi** [comment]
![filter-bug](https://cloud.githubusercontent.com/assets/112297/21004006/931b22ba-bd2e-11e6-83b5-87ec0150e8f1.gif)

newest chrome (55)

**Comment by dzucconi** [comment]
at the end there u cant tell but im clicking/trying to type

**Comment by broskoski** [comment]
I understand this now too, thank you.
