### ISSUE TITLE
Lightbox Q/A

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#406]
- [x] make sidebar section header fonts regular weight
- [x] blinking when loading images
- [x] info hidden - attribution (middle line) is a little too high
- [ ] clicking previous / next quickly in certain places accidentally selects text/image elements
- [x] 'show info' should be 2-3 pixels further inward  (on both right and bottom sides)
- [x] 'show info' and 'hide info' aren't aligned (hide looks lower)
- [x] for when there's a delay in loading connections, put a  throbber in that area?
- [x] 90% opacity background

**Comment by danpia** [comment]
- [ ] title div height: 100%; min-height: 50px;

**Comment by csherron** [comment]
- [ ] in channel metadata, There needs to be a line break before the connect button
<img width="214" alt="screen shot 2017-03-16 at 1 53 44 pm" src="https://cloud.githubusercontent.com/assets/3780330/24011051/fed6fb64-0a4f-11e7-96e4-b270b831481d.png">

**Comment by broskoski** [comment]
@csherron good catch, will fix
