### ISSUE TITLE
mobile web version quick tweaks

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#435]
tweaks for mobile web version only

- [x] make top bar opaque (i only notice this in browsers, not phone)
- [x] lightbox menu text (as well as description, source, connect, attribution etc) appears much smaller and slightly spaced out than the metadata text, with spacing inconsistencies as well - confirm things like line height 1.5, font size 13px and make sure sizes/spacing visually match
- [x] top bar: get rid of list/column view button while in feed (should apply to desktop site as well?)
- [ ] leave ‘follow’ and ‘connect’ buttons visible on channel and profile blocks
- [x] in lightbox, left chevron gets stuck
- [x] on blocks, connect button still visible in mobile landscape mode
- [x] tools page - remove tabs and just stack sections on top of each other
- [x] missing 'about' sections on profiles
- [x] adding collaborators - dropdown doesn't push everything else down, generally difficult to add people, and only pressing on the '+' and '-' adds/removes them (not their complete name)

**Comment by csherron** [comment]
tweaks for mobile web version only

- [ ] make top bar opaque (i only notice this in browsers, not phone)
- [ ] lightbox menu text (as well as description, source, connect, etc) appears much smaller and slightly spaced out than the metadata text, with spacing inconsistencies as well - confirm things like line height 1.5, font size 13px and make sure sizes/spacing visually match
- [ ] top bar: get rid of list/column view button while in feed (should apply to desktop site as well?)
- [ ] leave ‘follow’ and ‘connect’ buttons visible on channel and profile blocks
- [ ] in lightbox, left chevron gets stuck
- [ ] on blocks, connect button still visible in mobile landscape mode
- [ ] tools page - remove tabs and just stack sections on top of each other
- [ ] missing 'about' sections on profiles

**Comment by broskoski** [comment]
@csherron can you give me a screenshot to illustrate what you mean by "on blocks, connect button still visible in mobile landscape mode"
