### ISSUE TITLE
Infinite scroll throbber overlaps with blocks as they're loading

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#526]
## Steps to replicate

* Throttle your internet connection using Chrome network debugger
* Load the feed
* Scroll down

## Expected result
???

## Actual result
<img width="209" alt="screen shot 2017-05-14 at 9 00 19 am" src="https://cloud.githubusercontent.com/assets/3780330/26128420/66f5920c-3a5a-11e7-85e5-7b4cd15b14b6.png">

**Comment by dzucconi** [comment]
@csherron can you fill out the expected result here?
