### ISSUE TITLE
New profile/blocks QA

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#530]
- [x] under Sort "Recently updated" should be black when applied
- [x] html not rendering under About
- [x] some images have Source button on hover

**Comment by csherron** [comment]
New view modes

**All / Channels** (row view) **/ Blocks / Index** (index view)

row view
- [ ] missing "follow" and "start private channel" links under Info
- [ ] start rows 40px further down
- [ ] when browser is stretched out, container loses its center
- [ ] missing follow / connect hover on channels
- [ ] need throbber for loading new channel rows
 
index view
- [ ] remove focus thumbnails
- [ ] filter bar says "Filter Sort" should say "Filter X's Channels"
- [ ] channel borders make 0.3 opacity
