### ISSUE TITLE
new dropdown menu / bookmarklet / profile etc. QA

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#580]
## Logged in Navigation

- [x] new channel dropdown - make “type channel name” text the light channel color (same color as border) , remove gray background

- [x]  new channel dropdown - make privacy options text 0.95em (as to not compete with the ‘create channel’ button

- [x]  notifications dropdown - neither ‘notifications’ or ‘view all notifications’ buttons are clickable

- [x]  user dropdown - make ‘tools’ and ‘about and faq’ the smaller text style, just group them in the same section with ‘settings’ and ‘log out’

- [x]  user dropdown - add ‘Index’ to the top of the menu along with channels and blocks

- [x]  view dropdown - instead of greying out thumbnail / list view options, add a check mark to the right side of currently active view

- [x]  all dropdowns - margin top 45px (instead of 55px)

- [x]  user and notifications dropdowns - text overall has 5 px too much left/right padding

- [x]  notification dropdown - align notification items to the notifications header (instead of indenting them)

## Channel view

- [ ]  a few form mismatches in metadata: no border on collab form, x is misaligned on collab form, no border on export share link form

## Channels view

- [x] in 'channels' view - the filter bar just says "filter sort" instead of "filter User X's channels" 

- [x] noticing some block blinking when scrolling 

- [x] since adding filter bar to 'channels' view - block alignment is off from other view modes

- [x] top borders on "follow / connect" come out neon-isn

<img width="344" alt="screen shot 2017-05-31 at 5 03 50 pm" src="https://cloud.githubusercontent.com/assets/3780330/26654043/3b7ea5a8-4623-11e7-90b2-54ae57eec7a0.png">
 vs.
<img width="340" alt="screen shot 2017-05-31 at 5 03 44 pm" src="https://cloud.githubusercontent.com/assets/3780330/26654046/42fc7d14-4623-11e7-8cc0-c2bef9fc6cb5.png">

## Block view

- [x]  lightbox - info section padding is different (a little bit greater) than connections and comments section padding

- [x] https://github.com/aredotna/ervell/issues/573

- [x] https://github.com/aredotna/ervell/issues/588

## Bookmarklet

- [x]  bookmarklet - give a little bit more padding to everything (10px is not much and we don’t need to worry about how big this is overall)

- [x]  bookmarklet - overall bookmarklet needs 10px more padding so it’s not too far in the corner of the browser window

- [x]  bookmarklet - try best to match drop zone instruction text / dropped text itself with the current add block styles on the main site

- [x]  bookmarklet - thick gray border isn’t rounded

- [ ] maybe check mark on bookmarklet is deceiving since it hasn't been actually connected yet. for now just nix the checkmark 

- [x] bookmarklet sometimes shows up full width (i can only replicate it here http://www.documentjournal.com)

- [x] https://github.com/aredotna/ervell/issues/484

- [x] https://github.com/aredotna/ervell/issues/578

**Comment by dzucconi** [comment]
@csherron 

> bookmarklet - give a little bit more padding to everything (10px is not much and we don’t need to worry about how big this is overall)

I'm not sure what this means?
