### ISSUE TITLE
"blocks with this url" text spacing is off

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#601]
![screen shot 2017-06-01 at 1 06 00 pm](https://cloud.githubusercontent.com/assets/3780330/26692478/deb17114-46ce-11e7-8b27-ad5ac121352d.png)

**Comment by dzucconi** [comment]
This was intentional to match the headers. What should the spacing be?

**Comment by csherron** [comment]
sorry, if you can vertically center the text between the channels it would look the cleanest.
