### ISSUE TITLE
Close button not working on list-mode connect

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#654]

**Comment by dzucconi** [comment]
How to replicate?

**Comment by broskoski** [comment]
Make a connection and then try to close

**Comment by dzucconi** [comment]
I can't replicate

**Comment by broskoski** [comment]
![list-connect](https://user-images.githubusercontent.com/821469/26941304-0a9190ac-4c4c-11e7-9dd5-487feb8516ac.gif)

**Comment by dzucconi** [comment]
ok so this is a problem with list mode. it's not replicable with shorter channels, apparently.

**Comment by broskoski** [comment]
Can't replicate this now either, will reopen if I see it again
