### ISSUE TITLE
Channel metadata Q/A

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#666]
- [ ] Needs more vertical padding between metadata sections (try like 30px more)
- [ ] `.metadata__column` change bottom padding from 10px to ~50px
- [ ] Mobile metadata on profiles - missing view/sort
- [ ] Feedback on all interactions (click something & something tells you it's working, error states, success feedback with informative messages)
- [ ] Clear up permissions issues (Should not be rendering to the DOM the menu and hiding it with CSS, should not show delete when you can't delete... etcetera)
- [ ] Prevent content shift on load by setting a fixed header height +++++++++
- [ ] Remove border on collab form
- [ ] x is misaligned on collab form
- [ ] Remove border on export share link form

---
## Relevant feedbacks

* https://www.are.na/block/1074770

**Comment by dzucconi** [comment]
- [ ] Feedback on all interactions
- [ ] Clear up permissions issues

Re: https://www.are.na/block/1074770
