### ISSUE TITLE
In lightbox view, blocks without a title need an empty placeholder line in the title area

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#667]
## Expected result
The sidebar shouldn't move up and down as you page through blocks. For blocks that lack titles: an empty line should be rendered in the title's place.

## Actual result
The sidebar moves up and down. The title is removed completely.

**Comment by dzucconi** [comment]
What does this mean?

**Comment by csherron** [comment]
so that the sidebar doesn't jolt up and down as your advancing through items, we had it like this before but it's been removed

**Comment by dzucconi** [comment]
Right, so what should be there?

**Comment by csherron** [comment]
an empty line
