### ISSUE TITLE
blocks / display QA

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#672]
- [x] unfollowing from the ‘following’ page, no feedback, users stick around even after refreshing
- [x] no way to connect channels in mobile
- [x] cant click on text blocks after they’ve been repositioned in a channel
- [x] "add block" button needs a hoverstate
- [x] follow button missing on channel blocks in mobile

**Comment by broskoski** [comment]
What's `unfollowing from the ‘following’ page, no feedback, users stick around even after refreshing` mean? I can't replicate, can follow both users and the profile user in the following screen.

**Comment by csherron** [comment]
go to your following section in your profile - unfollow someone, their profile block remains there, even after a refresh

**Comment by dzucconi** [comment]
Assuming these are addressed from the checkmarks. Closing.
