### ISSUE TITLE
Mobile design tweaks, what happened to them?

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#674]
https://www.are.na/block/954001

https://www.are.na/block/954803

https://www.are.na/block/954005

https://www.are.na/block/953997

https://www.are.na/block/953996

**Comment by dzucconi** [comment]
These existed?

**Comment by csherron** [comment]
i remember cab showing them to me in staging a while ago

**Comment by broskoski** [comment]
I will re-issue these and pr my work in progress branch
