### ISSUE TITLE
Notification counter badge has a delay / flicker when loading each new page

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#676]
## Steps to replicate
* Have some number of unread notifications
* Load any page

## Expected result
Page immediately loads with the expected number of notifications.

## Actual result
Displays 0 results then loads fully and displays the correct amount.

**Comment by broskoski** [comment]
We aren't gonna fix this anytime soon I'm afraid, the fix is checking for notifications before the page loads, but that would add additional time to _every_ page load. Other alternatives are also less attractive. I'll keep this open in any case.

**Comment by dzucconi** [comment]
It'd be useful to locally cache it with a relatively short timeout, however. Would drastically cut down some requests too.

**Comment by dzucconi** [comment]
So, what I'm saying is: we can at least minimize this, a bit.
