### ISSUE TITLE
Add bottom page padding to logged out, mobile view of Block pages

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#691]
## Steps to replicate
* Visit any block page while logged out

## Expected result
Should have a "natural" amount of bottom margin between connection list and the page bottom

## Actual result
Lacks a margin (see screenshot)

![](http://static.damonzucconi.com/_capture/yBBzzLcrCe.png)

**Comment by dzucconi** [comment]
Sort of indicative to a general lack of thought about mobile in general.
