### ISSUE TITLE
Deployable Onboarding Q/A

### ISSUE THREAD

**Issue by dzucconi** [aredotna/ervell#693]
- [x] Mobile in general...
- [x] clickable steps to go back and forth, jump
- [x] `.OnboardingGuide__pane` padding-bottom same as padding-top
- [x] make bookmarklet and Twitter buttons same height of "Next" button, and background color #f7f7f7
- [x] `.FoundFriendsContact__identifier {max-width: 100%}`
- [x] make the "Next" and "Start using" buttons look active like in the previous steps
- [x] Final copy for explore
- [x] remove black bars from video if possible
- [x] remove pause and fullscreen buttons (https://vimeo.com/forums/help/topic:278001) 
- [x] remove "a, b, c," categorization, i feel like it's unnecessary 
- [x] move captions inline with the outline:
![screen_shot_2017-06-15_at_2 11 40_pm](https://user-images.githubusercontent.com/3780330/27602847-2f90349e-5b42-11e7-9ded-576eec037598.png)

- [x] when i'm logged out of twitter, i get a message on the 'find friends' section that says: "Try again later: The resource you are looking for does not exist."

**Comment by danpia** [comment]
- [ ] clickable steps to go back and forth, jump
- [ ] .OnboardingGuide__pane padding-bottom same as top padding
- [ ] make bookmarklet and Twitter buttons same height of "Next" button, and background color #f7f7f7
- [ ] `.FoundFriendsContact__identifier {max-width: 100%}`
- [ ] in steps 4 and 5 either add lil 'skip' into the actions, or make the "Next" and "Start using" buttons look active like in the previous steps

**Comment by dzucconi** [comment]
@danpia You'd have to be logged in for /welcome to work because you'd need an account to be onboarded

**Comment by dzucconi** [comment]
@danpia I need like a semantic meaning for the notion of giving a background color. I need a reason? How does this fit into the bigger picture of the UI?

**Comment by dzucconi** [comment]
Also why is there a skip if it does the exact thing as the next button right below it?

**Comment by danpia** [comment]
@dzucconi skip was meant so that Next button is not clickable/active unless you skip the action, but if it's too of a forceful stretch we can drop this.
