### ISSUE TITLE
Thumbnail outline suggestion

### ISSUE THREAD

**Issue by dzucconi** [aredotna/ervell#72]
Calculate the average value of a thumbnail and apply a border dependent upon whether or not it passes some kind of threshold. (It'd probably be easy to detect if an image was a solid white square, for instance)

![](http://static.damonzucconi.com/_capture/sr/lf5aq40v4ko04.png)

**Comment by broskoski** [comment]
+

**Comment by danpia** [comment]
+

**Comment by broskoski** [comment]
https://github.com/lokesh/color-thief

**Comment by dzucconi** [comment]
Still like this idea. An easier way to do this would be to just add a semi-transparent border that overlays 1px into the image. You wouldn't notice it on images that have some kind of coloring, but it would provide some context on images that are mostly white.
