### ISSUE TITLE
Video embeds are abnormally tall on blog posts

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#720]
## Steps to replicate
Visit a blog post with embedded video. Scroll towards the bottom of this post: https://are.na/blog/case%20study/2017/06/13/allyn-hughes.html

## Expected result
Videos should have a natural aspect ratio

## Actual result
Vides are as tall as embedded channels

## Speculation
Due to https://github.com/aredotna/ervell/pull/709/files#diff-8473aade0d9af8362aa46e6f88c2aa60R49 — Embedded channels should have styling specific to them; not generic `iframe`s.

------
![](http://static.damonzucconi.com/_capture/xRgJEMECoS.png)

**Comment by dzucconi** [comment]
Due to https://github.com/aredotna/ervell/pull/709/files#diff-8473aade0d9af8362aa46e6f88c2aa60R49

**Comment by dzucconi** [comment]
I think that this is fundamentally an issue with the way embedded channels are handled. We should not be doing that with CSS like this
