### ISSUE TITLE
When creating a new private channel from lightbox connect, channel connections are duplicated

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#727]
## Steps to replicate

* Page through lightbox blocks
* Connect any arbitrary block to any arbitrary channel (including one you're creating at that moment)

## Expected result
The single new channel connection is displayed above in the connections list

## Actual result
The connection is displayed as many times as blocks you've previously paged through.

## Speculation
The listener that adds to the connection list just re-binds. It's broken in a few ways (removal amongst them).

<img width="358" alt="screen shot 2017-06-30 at 12 43 17 pm" src="https://user-images.githubusercontent.com/3780330/27745745-8717061e-5d92-11e7-8b7f-7b0b19adf871.png">

**Comment by dzucconi** [comment]
Can you be more specific about steps to replicate?

**Comment by dzucconi** [comment]
Steps to replicate:

* Page through lightbox blocks
* Connect

The listener that adds to the connection list just re-binds. It's broken in a few ways (removal amongst them)
