### ISSUE TITLE
Homepage Q/A

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#753]
Above the fold:
- [x] Make "Log In" visible on top right corner
- [x] Replace the right side big button with "What is Are.na?" (click will autoscroll to below the fold)
- [x] Remove the current "What is Are.na?" 

As you start scrolling:
- [x] "Join or Log In" both visible on top right corner 

![screenshot 2017-07-06 15 02 07](https://user-images.githubusercontent.com/3718189/27932441-c6dc7012-626b-11e7-9de0-0e094bee14e4.png)

![screenshot 2017-07-06 15 04 31](https://user-images.githubusercontent.com/3718189/27932450-cc21d4e0-626b-11e7-81b6-fc11b153ccea.png)

![screenshot 2017-07-06 16 55 28](https://user-images.githubusercontent.com/3718189/27932506-f638d026-626b-11e7-9559-a62fe7947480.png)

**Comment by broskoski** [comment]
@danpia why kill the "Are.na" in the top left? Seems like this is making the page more ambiguous but for what reason?

**Comment by danpia** [comment]
@broskoski true, leave it
