### ISSUE TITLE
Search terms with hyphens do not return expected results

### ISSUE THREAD

**Issue by cbadal** [aredotna/ervell#761]
I experienced this issue in both Chrome and Chrome Incognito. 

# Steps to reproduce

Search any term with a hyphen (eg. self-care, co-working). 

# Expected result

At minimum, the results that appear while typing in search field.

<img width="716" alt="screen shot 2017-07-07 at 11 41 30 am" src="https://user-images.githubusercontent.com/5408357/27965457-da0d4910-6309-11e7-96a7-47c572e6c292.png">
<img width="830" alt="screen shot 2017-07-07 at 10 44 28 am" src="https://user-images.githubusercontent.com/5408357/27965458-da0f4832-6309-11e7-9227-758227deefdb.png">

# Actual result

Either zero results or just the first result listed while typing in search field. See results for searching [self-care](https://www.are.na/search/self-care) and [co-working](https://www.are.na/search/co-working):

<img width="912" alt="screen shot 2017-07-07 at 10 44 46 am" src="https://user-images.githubusercontent.com/5408357/27965436-cb4a2b50-6309-11e7-8d1a-8a3e14f0f751.png">
<img width="648" alt="screen shot 2017-07-07 at 11 41 37 am" src="https://user-images.githubusercontent.com/5408357/27965435-cb49c930-6309-11e7-9cf7-6f2d73267392.png">

**Comment by dzucconi** [comment]
### Related

Appears that query encoding in general is broken. This page should simply use an encoded query param. Searching for `http://google.com` hits: https://www.are.na/search/http://google.com — which 404s. Compare with the encoded: https://www.are.na/search/http%3A%2F%2Fgoogle.com

**Comment by danpia** [comment]
seems solved
