### ISSUE TITLE
in "Channels" view on profile - long channel names text overflows 

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#768]
<img width="402" alt="screen shot 2017-07-08 at 10 35 51 am" src="https://user-images.githubusercontent.com/3780330/27986182-8bcc4d08-63c9-11e7-8f8f-f8e86071953b.png">

**Comment by dzucconi** [comment]
There's not enough information to replicate this.

For instance I was going to provide a link to the issue (which you need to do) and it's fine in that context: https://www.are.na/damon-zucconi/overflowing-channel-title

Please everyone get in the habit of providing more information with these issues (steps to replicate, links to examples).

**Comment by csherron** [comment]
https://www.are.na/rachel-valinsky/channels
