### ISSUE TITLE
Comments display unwanted HTML

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#779]
![screen shot 2017-07-18 at 5 05 42 pm](https://user-images.githubusercontent.com/821469/28339834-7c7de39c-6bdb-11e7-86f6-52cafd93401f.png)

# Steps to reproduce
Input an image markdown tag or an image href into a block comment

# Expected result
The HTML gets stripped

# Actual Result
HTML gets parsed

**Comment by dzucconi** [comment]
Related https://github.com/aredotna/api/issues/215
