### ISSUE TITLE
Static pages QA/ CSS tweakage

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#808]
INCONSISTENCIES 
- [ ] general padding / positioning / sizing of the arena logo / logged out header fonts aren’t consistent with the logo / top bar typography when logged in - not sure what values to put here to make them totally match…
- [x] attached is an image that shows the inconsistencies with all the different headings, they all aught to match the landing page’s baseline
![headings](https://user-images.githubusercontent.com/3780330/28726504-7ec02820-738f-11e7-8af6-f1bdade464f4.jpg)

LANDING PAGE
- [x] .HomeNext button — change margin to 4em

LANDING PAGE (RESPONSIVE MOBILE VERSION ONLY)
- [x] .HomeSection__content  — add padding-bottom of 4em
- [x] .LoggedOutFooter — add padding-top of 4em

ABOUT PAGE
- [x] i strongly prefer the landing page CTA buttons to these small ones - the small ones feel a little lost in the mix, but if daniel or damon prefer them i’m willing to compromise
- [x] .AboutPost — add padding-top of 1.5em
- [x] replace twitter/instagram URL links with "Twitter" and "Instagram" hyperlinks

BLOG
- [x] in inspector i’m seeing h2.Type set to margin:1em auto; - this is screwing with the spacing between blog titles and the date, remove this value if you can and replace with:
- [x] .BlogPosts__post > h2 — make padding-bottom 0.5em
- [x] h5 (the timestamp) — make padding-bottom 1.5em
- [x] remove all the .PageNarrowBreakout stuff

BLOG SINGLE POST

- [x] make all iframe embeds 500px wide maximum
- [x] make arena embed iframe margin 4em
- [x] .post-content img — make margin 4em auto
- [x] .post-content p — make margin 2em auto
- [x] add 8em of whitespace to the bottom of every blog post (gives more breathing room between post and footer)

**Comment by danpia** [comment]
@csherron i'm ok with with big CTA buttons
