### ISSUE TITLE
unable to delete channel

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#811]
<img width="1439" alt="screen shot 2017-07-31 at 1 04 50 pm" src="https://user-images.githubusercontent.com/3780330/28788924-ea43d462-75f0-11e7-9a4e-82011de7b7b6.png">

**Comment by dzucconi** [comment]
Can we get some steps to replicate? @csherron

**Comment by danpia** [comment]
Happened to me as well (channel had a collaborator and it's private). Tried to replicate but seemed pretty random, I just had deleted a bunch of other channels and suddenly one wouldn't. When clicking 'Yes' to confirm simply nothing happens.

**Comment by broskoski** [comment]
@dzucconi pretty sure the request times out

**Comment by dzucconi** [comment]
Woof

**Comment by danpia** [comment]
just tried again now and it worked

**Comment by csherron** [comment]
i cant even remember what channel this was, gonna close
