### ISSUE TITLE
Onboarding Tweaks 03: Change profile and feed tips for new users

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#938]
## Profile

- [x] remove the current "empty state" sentence
- [x] change and restyle the current tips following the comp below
- [x] make the tips stick above the content until user closes them

![profile-tips](https://user-images.githubusercontent.com/3718189/32465595-07d68574-c312-11e7-997f-1c4200b1d509.png)

**Copy**
Welcome to Are.na! This is your profile. All your channels and connections will show up here.
	• 	Start adding content by creating your first channel. [opens channel creator]
	• 	Check out these favorite channels picked by the Are.na community. [link to https://www.are.na/are-na/classic-channels]

**UI**
_background: #f7f7f7, border-radius: 3px, font-size: 1.25rem font-size-lg_

## Feed/Explore
- [x] remove the current "empty state" sentence
- [x] add tips following the comp below
- [x] make the tips stick above the content until user closes them

![feed-tips](https://user-images.githubusercontent.com/3718189/32465770-aa72d260-c312-11e7-9ba6-c2b2384e4dd0.png)
**Copy**
This is your feed. Updates from the people and channels you follow will appear here.
	•	Go to Explore to see everything the Are.na community is connecting in real time. [link to explore]
	• 	Check out these favorite channels picked by the Are.na community. [link to https://www.are.na/are-na/classic-channels]

**UI**
_background: #f7f7f7, border-radius: 3px, font-size: 1.25rem font-size-lg_

**Comment by broskoski** [comment]
@danpia doesn't seem like a great idea to remove a tip about installing the bookmarklet, what's the rationale there?
