### ISSUE TITLE
Onboarding Tweaks 04: corner pop-up tips for new users

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#939]
Stacked, from top to bottom:
1. "**Find friends from Twitter** on Are.na" [link to https://www.are.na/tools/find-friends ]
_show 1. only to people who haven't connected_
2. "Save to Are.na faster with **the bookmarklet**" [link to https://www.are.na/tools/bookmarklet ]
3. "If you need help on how to use Are.na, read our **FAQs** or contact us at help@are.na" [link to https://www.are.na/faqs]

**Comment by broskoski** [comment]
@danpia I think we are gonna have to do something else with these, this seems a little nuts for a first time experience.
<img width="1395" alt="screenshot 2017-11-12 15 41 26" src="https://user-images.githubusercontent.com/821469/32703179-f87c5e66-c7bf-11e7-9dbe-8e8a5682c1da.png">
