### ISSUE TITLE
Onboarding Tweaks 05: Update FAQs copy

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#940]
**What should I use Are.na for?**
There is no right or wrong way to use Are.na. It's an open-ended space where you can organize your thoughts, projects, or research with anyone else. Play around for a while: adding content, connecting channels, and discovering new users are the best ways to get a feel for how Are.na works.

**How is Are.na different from other bookmarking and productivity sites?**
Built around simple collections that link together into expansive networks, Are.na represents a cooperative model for organizing media and ideas — free of ads, likes, algorithms, or distractions. Think of it as an organic archive of all kinds of knowledge, built by thoughtful people in order to learn and discover new things.

**What are channels?**
A channel is simply a collection of images, links, files, and texts. What it becomes is up to you and whoever you share it with. A channel can be a reading list, a research archive, a brainstorming canvas, or a mood board, but it can also be a mindmeld between collaborators, a calm headspace for your thoughts, or a poem. 

You can create your own channels and make them private, public, or open to invited collaborators only. 

**What's the difference between open, closed and private channels?**
Channels have privacy settings that determine who can view or add to them. Open channels are channels that anyone can view and add to. Closed channels can be seen by everyone, but can only be edited by invited collaborators. Private channels can only be seen or edited by invited collaborators.

You can choose the privacy setting when you create a channel. If a someone else makes an open channel or invites you to their closed channel, you can connect anything you see on Are.na to it.

**Where can I see examples of active users and content?**
Check out these favorite channels **[link to https://www.are.na/are-na/classic-channels]** picked by the Are.na community or go to the Explore **[link to Classic Channels]** page, which shows everything the Are.na community is connecting in real time.

**How do I collaborate with other people on Are.na?**
To invite someone to collaborate on your channel: open the channel and type their name under “Edit Collaborators” in the channel header. If they’re not on Are.na yet, you can invite them by entering their email address.

Channel owners and collaborators can update the order of a channel, change its visibility and change its title.

You can invite friends to sign up for Are.na by entering their email address here. You’ll automatically be following each other once they register.

![collaborator](https://user-images.githubusercontent.com/3718189/32470198-74d61c7c-c324-11e7-8078-78ca583e4342.gif)
_img width: 75%_
[gif source: https://d2w9rnfcy7mm78.cloudfront.net/1401809/original_cf115365cb891ba730021131366e4368.gif ]

**Can I export my channels?**
Yes, you can export the contents of any channel in ZIP, PDF and html formats. Look for the Export menu in the channel header.

![export](https://user-images.githubusercontent.com/3718189/32470217-8c9097e8-c324-11e7-8d9e-17dafd63c21c.gif)
_img width: 75%_
[gif source: https://d2w9rnfcy7mm78.cloudfront.net/1401806/original_72c94421d59560afbe88c1aeb8001935.gif ]

**How do I delete a block?**
To remove a block from one of your channels, open the channel and hover on the block you want to remove. Click the trash icon on the top corner.

![delete](https://user-images.githubusercontent.com/3718189/32470228-9d7d1482-c324-11e7-91e0-05590d7da04c.gif)
_img width: 75%_
[gif source: https://d2w9rnfcy7mm78.cloudfront.net/1401808/original_7a00fc67159c98ea4a4254e4d5eaceee.gif ]

**What is the Are.na bookmarklet?**
The Save to Are.na bookmarklet makes it easy to add content to any channel from your browser bar while you are out and about surfing the net. You can install it in one step here **[link to https://www.are.na/tools/bookmarklet]**.

**Is there an Are.na mobile app?**
There will be an Are.na mobile app very soon! We’ll be announcing the release in November 2017.

**How do I hide my public channels and profile from search engines?**
Premium **[link to https://www.are.na/about#premium]** members have the option to completely opt out from search engine crawlers.

**I'm still lost and I’m not sure how to use Are.na. Can you help?**
You can go through the getting started tutorial **[link to https://www.are.na/welcome/channels]** or contact us at help@are.na

**How do I delete my account?**
Please get in touch with help@are.na and we’ll take care of it. 

**Who owns Are.na?**
100% of shares are owned by the founders and advisors.

**How do you make money?**
Our goal is to sustain Are.na through the support of our loyal Premium **[link to https://www.are.na/about#premium]** members. We do not sell members’ data or advertising space. Read more about our philosophy and mission here **[link to https://www.are.na/about]**.

**Do you have an API documentation?**
You can find our API documentation here: dev.are.na. FYI, it’s a bit out of date.

**What sites are built on Are.na's API?**
Here is a list **[link to https://www.are.na/are-na/powered-by-are-na]** of projects powered by Are.na.

**Can I suggest features?**
We’d love to hear your ideas. Please post any suggestions and comments in our feedback channel **[link to https://www.are.na/are-na/feedback-and-feature-requests]**.

**Are there any restrictions on kind of content?**
We trust our members common sense, and we don't ban graphic or adult content in order to preserve their freedom to research freely. Our team will delete content from Are.na in the case of abuse, harassment, or criminal offense. Read our terms and conditions for more information **[link to https://www.are.na/terms]**.

**Can I only add content I own?**
Users are responsible for the content they link or upload. For research purposes we believe in the fair use of intellectual property, but please credit authorship and sources. Read our terms and conditions for more information **[link to https://www.are.na/terms]**.

**Is there a public product roadmap?**
These are the features we’re working on **[link to https://github.com/aredotna/ervell/projects/1]**.

**Should you thank someone?**
We are grateful to our early supporters and collaborators: Rafael Rozendaal, Laurel Schwulst, Harm van den Dorpel, Anne Spalter, Joel Holmberg, Bryce Wilner, Adam Sammons, Loic Bernasconi, Esen Karol, Splnlss, Chris Coy, Mike Tully, Nick DeMarco, Csaba Osvath, Nick Moore, Zach Rose, David Hilmer Rex, David Berezin, Julia Panek, Cleopatra's US, Juliana Romano, Grace Robinson-Leo, Alexandros Stamatelatos, Robert D Matthews, Aslak Aamot Kjærulff, James Chae, Christopher Pappas, Elizabeth Sutherland, Sun An, John Michael Boling, Dena Yago, Dan Brewster, Stuart Moore, Morgan Sutherland, Amelia Hall.

**How can I contact you?**
For general communications, send us an email at info@are.na. For bugs and technical questions, email help@are.na

**Comment by warshawshaw** [comment]
* On second thought it might be best to break up the first question into **What should I use Are.na for?"** and **"How is Are.na different from other bookmarking and productivity sites?"** 
<br> 
For the first: "There is no right or wrong way to use Are.na. It's an open-ended space where you can organize your thoughts, projects, or research with anyone else. Play around for a while: adding content, connecting channels, and discovering new users are the best ways to get a feel for how Are.na works."
<br>
For the second: "Built around simple collections that link together into expansive networks, Are.na represents a cooperative model for organizing media and ideas — free of ads, likes, algorithms, or distractions. Think of it as an organic archive of all kinds of knowledge, built by thoughtful people in order to learn and discover new things."
<br>
* There's a capitalization typo under **content restrictions**: "In the case of abuse"
* Also under **content restrictions**, I might phrase it like this: "We trust our members common sense, and we don't ban graphic or adult content in order to preserve their freedom to research freely."

**Comment by warshawshaw** [comment]
damn I'm terrible at markdown sorry
