### ISSUE TITLE
Onboarding Tweaks 06: Update onboarding tutorial copy

### ISSUE THREAD

**Issue by danpia** [aredotna/ervell#941]
### **Welcome**

Welcome to Are.na
Start creating channels, saving content, and making connections 

### Channels
**What’s a channel?**
Channels are the collections of content that make up Are.na. 
They can be open to everyone, closed to collaborators only, or completely private.
		
**Finding and adding to channels**
Create your own channels or share them with other members. You can add anything you see on Are.na to any open channel.

### Connecting
You can add almost anything to a channel. Drag and drop files, paste a link, or try the Are.na bookmarklet. 
Once you’re on Are.na, just click “Connect” on anything to add it to another channel.

### Browsing Are.na
**Profile**
Your profile shows all of your channels and connections in one place.

**Feed**
Your feed shows new connections by everyone you follow on Are.na.

**Explore**
Explore shows connections and channels made by everyone on Are.na, in real time.

### Save to Are.na
The Are.na bookmarklet lets you save content from any web page to your channels in a few clicks.
[Drag this box onto your bookmarks bar]

### Find friends
[Connect your Twitter account]

**Comment by warshawshaw** [comment]
* 2nd sentence under **What's a channel?** needs a period
* Remove "Just" before "drag and drop files" under  **Connecting**
* Sentence under **Save to Are.na** needs a period

**Comment by danpia** [comment]
done
