### ISSUE TITLE
Confirmation email message is above onboarding page

### ISSUE THREAD

**Issue by broskoski** [aredotna/ervell#954]
![screenshot 2017-11-13 18 29 43](https://user-images.githubusercontent.com/821469/32754919-dff60e64-c8a0-11e7-9a83-a08dd24fd1d2.png)

**Comment by dzucconi** [comment]
This should only be the case if you refresh the page once u get there. Feel free to add any routes to this https://github.com/aredotna/ervell/blob/3b4cb1d5f242ee641747d13bdc08f1740c001bcc/components/confirmable_message/index.styl#L30

**Comment by broskoski** [comment]
Ok I shall, but FYI I went straight from the welcome screen to the onboarding steps.

**Comment by dzucconi** [comment]
Then something else is wrong
