### ISSUE TITLE
Block-add debounce

### ISSUE THREAD

**Issue by msutherl** [aredotna/ervell#959]
## Problem

1. Paste a link in a channel to add a new block
2. Click "Add block" twice
3. Sometimes, two blocks are added

Normally, you don't want this.

## Solution

This seems to attempt to prevent this: https://github.com/aredotna/ervell/blob/f928e297e786df8947b8cbf9113cc6388224dad9/components/add_block/client/view.coffee#L77. Can't figure out why it might not work.

**Comment by broskoski** [comment]
Sorry @msutherl we haven't been able to replicate this! Feel free to re-open if you see it again.
