### ISSUE TITLE
CTA footer bar is missing on logged out channels

### ISSUE THREAD

**Issue by csherron** [aredotna/ervell#986]
_edited by cab_
- [ ] If the page is a channel, and the channel is open, change the copy to "Sign up for Are.na to add to [channel title]"
- [ ] if the page is a channel and the channel is closed, copy should be "Sign up for Are.na to follow [channel title]"
- [ ] if the page is a profile, copy should be "Sign up for Are.na to follow [username]"
- [ ] if none of these apply (private share link or block), the copy should be "Are.na is a platform for creative and collaborative research"

**Comment by broskoski** [comment]
And if the page is a channel, and the channel is open, change the copy to "Sign up for Are.na to add to this channel"
